version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - redis
     
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    networks:
      - redisnet  

  redis:
    image: redis:latest
    networks:
      - redisnet
    ports:
      - "6379:6379"

