version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - redis
    network_mode: "host"

    restart: "on-failure"
    

  redis:
    image: redis:latest

    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0
    
    